In [1]:
import pandas as pd
import csv
import numpy as np
import tensorflow as tf
import statistics

In [2]:
data=pd.read_csv("train.csv")

In [3]:
data.tail(1000)

row_id             time  x  y  direction  congestion
847835  847835   9/30/1991 6:40  2  0          2          66
847836  847836   9/30/1991 6:40  2  0          3          55
847837  847837   9/30/1991 6:40  2  0          1          70
847838  847838   9/30/1991 6:40  2  1          0          64
847839  847839   9/30/1991 6:40  2  1          2          40
...        ...              ... .. ..        ...         ...
848830  848830  9/30/1991 11:40  2  3          2          54
848831  848831  9/30/1991 11:40  2  3          4          28
848832  848832  9/30/1991 11:40  2  3          3          68
848833  848833  9/30/1991 11:40  2  3          7          17
848834  848834  9/30/1991 11:40  2  3          1          24

[1000 rows x 6 columns]

In [4]:
data

row_id             time  x  y  direction  congestion
0            0    4/1/1991 0:00  0  0          0          70
1            1    4/1/1991 0:00  0  0          2          49
2            2    4/1/1991 0:00  0  0          3          24
3            3    4/1/1991 0:00  0  1          0          18
4            4    4/1/1991 0:00  0  1          2          60
...        ...              ... .. ..        ...         ...
848830  848830  9/30/1991 11:40  2  3          2          54
848831  848831  9/30/1991 11:40  2  3          4          28
848832  848832  9/30/1991 11:40  2  3          3          68
848833  848833  9/30/1991 11:40  2  3          7          17
848834  848834  9/30/1991 11:40  2  3          1          24

[848835 rows x 6 columns]

In [5]:
data2=pd.read_csv("test.csv")

In [6]:
data2

row_id             time  x  y  direction
0     848835  9/30/1991 12:00  0  0          0
1     848836  9/30/1991 12:00  0  0          2
2     848837  9/30/1991 12:00  0  0          3
3     848838  9/30/1991 12:00  0  1          0
4     848839  9/30/1991 12:00  0  1          2
...      ...              ... .. ..        ...
2335  851170  9/30/1991 23:40  2  3          2
2336  851171  9/30/1991 23:40  2  3          4
2337  851172  9/30/1991 23:40  2  3          3
2338  851173  9/30/1991 23:40  2  3          7
2339  851174  9/30/1991 23:40  2  3          1

[2340 rows x 5 columns]

In [53]:
train_row_id=[]
train_time=[]
train_x=[]
train_y=[]
train_direction=[]
target=[]

In [54]:
with open("train.csv","r") as csv_file:
    reader=csv.reader(csv_file,delimiter=",")
    next(reader)
    for row in reader:
        train_row_id.append(int(row[0]))
        row[1]=row[1].replace(row[1][0:10],"")
        row[1]=row[1].replace(":","")
        row[1]=row[1][0:5]
        train_time.append(int(row[1]))
        train_x.append(int(row[2]))
        train_y.append(int(row[3]))
        train_direction.append(int(row[4]))
        target.append(int(row[5]))
        
    

In [55]:
len(train_row_id)

848835

In [10]:
len(train_time)

848835

In [56]:
train_time=np.array(train_time).astype(float)

In [57]:
train_time=train_time/2400

In [58]:
len(train_x)

848835

In [59]:
len(train_y)

848835

In [60]:
len(train_direction)

848835

In [61]:
len(target)

848835

In [62]:
train_X=list(zip(train_time,train_x,train_y,train_direction))

In [63]:
train_X[1000]

(0.0, 1, 1, 3)

In [64]:
target[1:10]

[49, 24, 18, 60, 58, 26, 31, 49, 46]

In [66]:
train_X=np.array(train_X,dtype="float32")

In [67]:
test_row_id=[]
test_time=[]
test_x=[]
test_y=[]
test_direction=[]


In [68]:
with open("test.csv","r") as csv_file:
    reader=csv.reader(csv_file,delimiter=",")
    next(reader)
    for row in reader:
        test_row_id.append(int(row[0]))
        row[1]=row[1].replace(row[1][0:10],"")
        row[1]=row[1].replace(":","")
        row[1]=row[1][0:5]
        test_time.append(int(row[1]))
        test_x.append(int(row[2]))
        test_y.append(int(row[3]))
        test_direction.append(int(row[4]))
        
        

In [69]:
len(test_x)

2340

In [70]:
len(test_y)

2340

In [71]:
len(test_direction)

2340

In [72]:
len(test_row_id)

2340

In [73]:
len(test_time)

2340

In [74]:
test_time=np.array(test_time,dtype="float32")

In [75]:
test_time=test_time/2400

In [76]:
test_X=list(zip(test_time,test_x,test_y,test_direction))

In [77]:
test_X=np.array(test_X,dtype="float32")

In [78]:
test_X[1:10]

array([[0.5, 0. , 0. , 2. ],
       [0.5, 0. , 0. , 3. ],
       [0.5, 0. , 1. , 0. ],
       [0.5, 0. , 1. , 2. ],
       [0.5, 0. , 1. , 3. ],
       [0.5, 0. , 1. , 1. ],
       [0.5, 0. , 2. , 0. ],
       [0.5, 0. , 2. , 2. ],
       [0.5, 0. , 2. , 3. ]], dtype=float32)

In [79]:
validation_X=train_X[800000:]

In [80]:
train_X=train_X[:800000]

In [81]:
print(train_X.shape)

(800000, 4)


In [82]:
train_Y=np.array(target,dtype="float32")

In [83]:
validation_Y=train_Y[800000:]

In [84]:
train_Y=train_Y[:800000]

In [85]:
print(train_Y.shape)

(800000,)


In [86]:
model = tf.keras.Sequential([
    tf.keras.layers.InputLayer(input_shape=(4,)),
    tf.keras.layers.Dense(1024,activation='relu'),
    tf.keras.layers.Dense(512,activation='relu'),
    tf.keras.layers.Dense(256,activation='relu'),
    tf.keras.layers.Dense(512,activation='relu'),
    tf.keras.layers.Dense(128,activation="relu"),
    tf.keras.layers.Dense(64,activation="relu"),
    tf.keras.layers.Dense(1)

])

In [87]:
model.compile(loss="mae",optimizer="adam",metrics=["accuracy"])

In [88]:
model.fit(train_X,train_Y,validation_data=(validation_X,validation_Y),batch_size=64,epochs=30)

Epoch 1/30
12500/12500 [==============================] - 97s 6ms/step - loss: 8.4407 - accuracy: 5.7500e-05 - val_loss: 7.8440 - val_accuracy: 4.0954e-05
Epoch 2/30
12500/12500 [==============================] - 83s 7ms/step - loss: 7.8264 - accuracy: 5.7500e-05 - val_loss: 7.5442 - val_accuracy: 4.0954e-05
Epoch 3/30
12500/12500 [==============================] - 94s 8ms/step - loss: 7.7243 - accuracy: 5.7500e-05 - val_loss: 7.3581 - val_accuracy: 4.0954e-05
Epoch 4/30
12500/12500 [==============================] - 92s 7ms/step - loss: 7.6706 - accuracy: 5.7500e-05 - val_loss: 7.4021 - val_accuracy: 4.0954e-05
Epoch 5/30
12500/12500 [==============================] - 91s 7ms/step - loss: 7.6271 - accuracy: 5.7500e-05 - val_loss: 7.4098 - val_accuracy: 4.0954e-05
Epoch 6/30
12500/12500 [==============================] - 95s 8ms/step - loss: 7.6063 - accuracy: 5.7500e-05 - val_loss: 7.3118 - val_accuracy: 4.0954e-05
Epoch 7/30
12500/12500 [==============================] - 99s 8ms/step

In [122]:
prediction=model.predict(test_X)

In [123]:
len(prediction)

2340

In [125]:
prediction=np.around(prediction)

In [124]:
test_row_id=test_row_id.tolist()

AttributeError: 'list' object has no attribute 'tolist'

In [127]:
prediction

array([[49.],
       [37.],
       [49.],
       ...,
       [70.],
       [16.],
       [43.]], dtype=float32)

In [134]:
final_pred=prediction.astype(int)

In [135]:
final_pred

array([[49],
       [37],
       [49],
       ...,
       [70],
       [16],
       [43]])

In [136]:
list_pred=final_pred.tolist()

In [137]:
list_pred

[[49],
 [37],
 [49],
 [27],
 [70],
 [61],
 [42],
 [49],
 [59],
 [63],
 [39],
 [30],
 [36],
 [33],
 [61],
 [30],
 [39],
 [57],
 [57],
 [62],
 [39],
 [38],
 [39],
 [57],
 [56],
 [59],
 [55],
 [72],
 [54],
 [51],
 [65],
 [63],
 [66],
 [41],
 [66],
 [55],
 [65],
 [42],
 [44],
 [67],
 [69],
 [51],
 [75],
 [73],
 [34],
 [21],
 [29],
 [36],
 [34],
 [47],
 [53],
 [65],
 [59],
 [35],
 [21],
 [68],
 [29],
 [55],
 [74],
 [47],
 [59],
 [27],
 [70],
 [19],
 [44],
 [49],
 [37],
 [50],
 [27],
 [70],
 [61],
 [42],
 [49],
 [60],
 [63],
 [39],
 [30],
 [37],
 [33],
 [61],
 [30],
 [39],
 [57],
 [58],
 [62],
 [39],
 [38],
 [40],
 [58],
 [57],
 [59],
 [56],
 [72],
 [55],
 [51],
 [65],
 [64],
 [66],
 [41],
 [66],
 [55],
 [65],
 [42],
 [44],
 [67],
 [69],
 [51],
 [76],
 [74],
 [35],
 [21],
 [29],
 [36],
 [34],
 [47],
 [54],
 [66],
 [61],
 [36],
 [21],
 [68],
 [30],
 [55],
 [74],
 [47],
 [59],
 [27],
 [70],
 [18],
 [44],
 [49],
 [37],
 [50],
 [27],
 [70],
 [62],
 [43],
 [50],
 [60],
 [63],
 [39],
 [30],
 [37],

In [148]:
df=pd.DataFrame({"row_id":test_row_id,"congestion":list_pred})

In [149]:
df["congestion"]=df["congestion"].str[0]

In [150]:
df

row_id  congestion
0     848835          49
1     848836          37
2     848837          49
3     848838          27
4     848839          70
...      ...         ...
2335  851170          67
2336  851171          29
2337  851172          70
2338  851173          16
2339  851174          43

[2340 rows x 2 columns]

In [151]:
df=df.to_csv("final_submission.csv",index=False)